// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::FlatBuffers;

public struct RoleLevelList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RoleLevelList GetRootAsRoleLevelList(ByteBuffer _bb) { return GetRootAsRoleLevelList(_bb, new RoleLevelList()); }
  public static RoleLevelList GetRootAsRoleLevelList(ByteBuffer _bb, RoleLevelList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RoleLevelList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public RoleLevel? RoleLevels(int j) { int o = __p.__offset(4); return o != 0 ? (RoleLevel?)(new RoleLevel()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int RoleLevelsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<RoleLevelList> CreateRoleLevelList(FlatBufferBuilder builder,
      VectorOffset RoleLevelsOffset = default(VectorOffset)) {
    builder.StartObject(1);
    RoleLevelList.AddRoleLevels(builder, RoleLevelsOffset);
    return RoleLevelList.EndRoleLevelList(builder);
  }

  public static void StartRoleLevelList(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddRoleLevels(FlatBufferBuilder builder, VectorOffset RoleLevelsOffset) { builder.AddOffset(0, RoleLevelsOffset.Value, 0); }
  public static VectorOffset CreateRoleLevelsVector(FlatBufferBuilder builder, Offset<RoleLevel>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateRoleLevelsVectorBlock(FlatBufferBuilder builder, Offset<RoleLevel>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartRoleLevelsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<RoleLevelList> EndRoleLevelList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RoleLevelList>(o);
  }
};


}
