// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::FlatBuffers;

public struct SkillDataList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static SkillDataList GetRootAsSkillDataList(ByteBuffer _bb) { return GetRootAsSkillDataList(_bb, new SkillDataList()); }
  public static SkillDataList GetRootAsSkillDataList(ByteBuffer _bb, SkillDataList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public SkillDataList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SkillData? SkillDatas(int j) { int o = __p.__offset(4); return o != 0 ? (SkillData?)(new SkillData()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int SkillDatasLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<SkillDataList> CreateSkillDataList(FlatBufferBuilder builder,
      VectorOffset SkillDatasOffset = default(VectorOffset)) {
    builder.StartObject(1);
    SkillDataList.AddSkillDatas(builder, SkillDatasOffset);
    return SkillDataList.EndSkillDataList(builder);
  }

  public static void StartSkillDataList(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddSkillDatas(FlatBufferBuilder builder, VectorOffset SkillDatasOffset) { builder.AddOffset(0, SkillDatasOffset.Value, 0); }
  public static VectorOffset CreateSkillDatasVector(FlatBufferBuilder builder, Offset<SkillData>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateSkillDatasVectorBlock(FlatBufferBuilder builder, Offset<SkillData>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartSkillDatasVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<SkillDataList> EndSkillDataList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<SkillDataList>(o);
  }
};


}
